# Generated by Django 4.1 on 2022-09-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_tasktodolist_delete_classtodolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktodolist',
            old_name='status',
            new_name='is_finished',
        ),
    ]
